title: Christoph Treude
logo: /assets/img/christoph.jpg
description: ARC DECRA Fellow, School of Computer Science, University of Adelaide
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
