title: Christoph Treude
logo: /assets/img/christoph.jpg
description: Associate Professor of Computer Science, Singapore Management University
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
